### PR TITLE
Add Maven

### PR DESCRIPTION
**Pull request by Nicolas-Gatien**
Added the Maven social media platform: https://www.heymaven.com/

### CODE REVIEW

**Comment by peppapig13132** [comment]
Thank you for your contribution!

And re-read [this guide](https://github.com/peppapig13132/social-media/blob/main/CONTRIBUTING.md#-adding-a-new-social-media-platform-data) again for code commit 😊.

**Comment by Nicolas-Gatien** [comment]
@peppapig13132 -- Making sure I got it before I change something, is the name of the commit message wrong? It's "Added Maven" instead of "Add Maven"?

**Comment by peppapig13132** [comment]
You're right. In general, commit messages should be in the imperative mood, like giving a command. So, "Add Maven" is more appropriate than "Added Maven." The imperative tense ("Add") makes the commit message read as a description of what the commit does, rather than what was done in the past.

**Comment by Nicolas-Gatien** [comment]
@peppapig13132 -- cool, that makes a lot of sense actually. Thanks for explaining! :D

**Pull request merged**
